name: Deploy to AWS CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Create .env file
        run: |
          touch .env
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env
          echo "VITE_LOG_LEVEL=${{ secrets.VITE_LOG_LEVEL }}" >> .env
          echo "VITE_API_TIMEOUT=${{ secrets.VITE_API_TIMEOUT }}" >> .env
          # Adicione uma linha para cada variável que seu projeto precisar

      - name: Build Project
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3 (Main Distribution )
        run: |
          aws s3 sync --delete ./dist/public s3://${{ secrets.DEPLOY_BUCKET }}

      - name: Invalidate CloudFront Cache (Main Distribution )
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} \
            --paths "/*"
